version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "comments-database"
    ports:
      - "5432:5432"
    enviroment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    network:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build:
    container_name: "comments-rest-api"
    enviroment:
      - POSTGRES_DB: "postgres"
      - POSTGRES_USER: "postgres"
      - DB_DB: "postgres"
      - DB_HOST: "db"
      - DB_TABLE: "postgres"
      - DB_PORT: "5432"
      - SLL_MODE: "disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
    network:
      - fullstack

volumes:
  database_postgres:

network:
  fullstack:
    driver: bridge
